# Generated by Django 4.2.6 on 2024-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
