# Generated by Django 5.0.7 on 2024-07-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCurrent',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.stockcurrent')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('bill_to_party', models.CharField(max_length=255)),
                ('gstin_B', models.CharField(max_length=15)),
                ('ship_to_party', models.CharField(max_length=255)),
                ('gstin_s', models.CharField(max_length=15)),
                ('hsn_code', models.CharField(max_length=20)),
                ('rate_of_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.stockin')),
            ],
        ),
    ]
