# Generated by Django 5.0.7 on 2024-07-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_stockcurrent_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='material',
        ),
        migrations.AddField(
            model_name='stockin',
            name='stockin_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockcurrent',
            name='m_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.stockcurrent'),
        ),
    ]
