# Generated by Django 5.0.7 on 2024-07-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0002_initial'),
    ]

    operations = [
        
    ]
