# Generated by Django 5.0.7 on 2024-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='stock_in',
        ),
        migrations.AlterField(
            model_name='stockin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
