# Generated by Django 5.0.7 on 2024-07-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_alter_stockin_stockin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='stockin_id',
        ),
        migrations.AlterField(
            model_name='stockin',
            name='m_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='billing_app.stockcurrent'),
        ),
    ]
