# Generated by Django 5.0.7 on 2024-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_initial'),
    ]

    operations = [
       
    ]
