# Generated by Django 5.0.7 on 2024-07-18 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0005_remove_bill_stock_in_alter_stockin_id'),
    ]

    operations = [
       
    ]
